version: '3.0'

services:
  web:
    build: .
    image: elazarcoh/madness
    volumes: 
      - type: bind
        source: ./docs
        target: /docs
    ports: 
      - 31000:3000

    deploy:
      restart_policy:
        condition: on-failure